name: erca
channels:
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip
  - bokeh
  - cartopy
  - xarray==2025.1.0
  - cftime==1.6.3
  - intake==2.0.8
  - intake-esm=2021.8.17
  - intake-xarray=0.6.0
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib=3.8.0
  - numpy=1.26.4
  - pandas=2.3.3
  - pyviz_comms=2.2.1
  - scipy=1.11.1
  - seaborn=0.11.2
  - pip:
    - aiohttp==3.8.1
    - aioitertools==0.10.0
    - aiosignal==1.2.0
    - dask==2022.5.0
    - holoviews==1.15.3
    - hvplot==0.8.2
    - netcdf4==1.5.8
    - panel==0.14.2
    - pangeo-forge-recipes==0.8.3
    - pymannkendall==1.4.2
    - zarr==2.11.3
