name: erca
channels:
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - pip=21.2.4
  - python=3.9.7
  - pyviz_comms=2.2.1
  - pip:
    - aiohttp==3.8.1
    - aioitertools==0.10.0
    - aiosignal==1.2.0
    - attrs==25.4.0
    - bokeh==3.4.3
    - cartopy==0.23.0
    - cdsapi==0.7.7
    - cftime==1.6.3
    - dask==2024.1.0
    - ecmwf-datastores-client==0.4.2
    - haversine==2.7.0
    - holoviews==1.20.2
    - hvplot==0.11.3
    - intake==2.0.8
    - intake-esm==2023.11.10
    - intake-xarray==2.0.0
    - markdown-it-py==3.0.0
    - matplotlib
    - netcdf4==1.5.8
    - numpy==1.23.0
    - pandas==2.3.3
    - pangeo-forge-recipes==0.8.3
    - proplot==0.9.7
    - pygrib==2.1.4
    - pyhdf==0.10.5
    - pymannkendall==1.4.3
    - pyproj==3.5.0
    - pyviz-comms==2.2.1
    - rasterio==1.4.3
    - scipy==1.11.1
    - seaborn==0.13.2
    - shapely==2.0.6
    - xarray==2024.1.0
    - zarr==2.18.2

